module.exports = {
  branchPrefix: "renovate/",
  branchPrefixOld: "main",
  username: "renovate-singnet[bot]",
  gitAuthor: "Renovate Bot <bot@renovateapp.com>",
  onboarding: false,
  requireConfig: false,
  platform: "github",
  forkProcessing: "disable",
  repositories: ["singnet/Omega"],
  extends: ["config:recommended"],
  dependencyDashboardAutoclose: true,
  prCreation: "approval",
  prConcurrentLimit: 0,
  reviewers: ["anseliv", "vsbogd"],
  packageRules: [
    {
      description: "lockFileMaintenance",
      matchUpdateTypes: [
        "pin",
        "digest",
        "patch",
        "minor",
        "major",
        "lockFileMaintenance",
      ],
      minimumReleaseAge: "3",
    },
  ],
};
